# Timeout for complete build. Default is 10m.
timeout: 7200s

############################################################################
# BUILD ARTIFACTS
############################################################################

steps:
# Fetch all submodules.
#- name: gcr.io/cloud-builders/git
#  args: [
#    'submodule', 'update', '--init', '--recursive'
#  ]

# Prepare yaml file.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
   - -c
   - python environment_bootstrap.py sandbox

- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
   - -c
   - env
  env:
   - 'COMMIT=$COMMIT_SHA'
   - 'TAG=$TAG_NAME'
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'
   - 'REGEXP_mlab_sandbox=mlab[1-4].[a-z]{3}[0-9]t.*'
   - 'REGEXP_mlab_staging=(mlab4.[a-z]{3}[0-9]{2}|mlab3.(lax02|lga03)).*'
   - 'REGEXP_mlab_oti=mlab[1-3].[a-z]{3}[0-9]{2}.*'

- name: gcr.io/cloud-builders/gcloud
  args: [
      'app', 'deploy', '--promote', 'app.yaml'
  ]
  dir: 'server'

