# Timeout for complete build. Default is 10m.
timeout: 1800s

############################################################################
# Deployment
############################################################################

steps:
# Setup per-project configuration.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
   - -c
   - python environment_bootstrap.py sandbox

# TODO: run unit tests.

# Report environment as a test.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
   - -c
   - env
  env:
   - 'COMMIT=$COMMIT_SHA'
   - 'TAG=$TAG_NAME'
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'

# Perform deployment of AppEngine service.
- name: gcr.io/cloud-builders/gcloud
  args: [
      'app', 'deploy', '--promote', 'app.yaml'
  ]
  dir: 'server'

