# Timeout for complete build. Default is 10m.
timeout: 1800s

############################################################################
# Deployment
############################################################################

steps:
# Create the image for testing mlab-ns.
- name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'mlabns-tester', '.'
  ]

# Run unit tests for environment.
- name: mlabns-tester
  # "build" runs all unit tests.
  entrypoint: /workspace/build
  env:
   - 'COMMIT=$COMMIT_SHA'
   - 'TAG=$TAG_NAME'
   - 'PROJECT=$PROJECT_ID'

# Perform deployment of AppEngine service.
#- name: gcr.io/cloud-builders/gcloud
#  args: [
#      'app', 'deploy', '--promote', 'app.yaml'
#  ]
#  dir: 'server'

