runtime: python27
api_version: 1
threadsafe: false
instance_class: F4_1G

handlers:

- url: /images
  static_dir: mlabns/images

- url: /stylesheets
  static_dir: mlabns/stylesheets

- url: /favicon.ico
  static_files: mlabns/images/favicon.ico
  upload: mlabns/images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /(admin|map).*
  script: main.app
  #login: required

- url: /oauth2callback
  script: oauth2client/appengine.py

- url: /cron
  script: main.app
  login: admin

- url: /.*
  script: main.app

builtins:
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: django
  version: "1.2"

- name: webapp2
  version: 2.5.1

- name: jinja2
  version: 2.6

includes:
- mapreduce/include.yaml
